### ISSUE TITLE
how to switch from in_memory(default) to local_disk ?

### ISSUE THREAD

**Issue by zbhuang** [cdmh/mapreduce#5]
Firstly, thanks for your work. I played with your program, and debug in and also read google's mapreduce paper, and got better understanding of it.
I have one questions to ask.
how to switch from in_memory to local_disk ?
Two methods for intermediates and two methods for schedule_policy. If I switch from cpu_parallel to sequential (basically just replace it in mapreduce.hpp and wordcount.cpp files, build the project, and run it. But when I did the similar change to in_memory (replace it with local_disk in job.hpp file), then I got the build the error - "local_disk.hpp(640): error C2679: binary '>>' : no operator found which takes a right-hand operand of type 'std::pair<_Ty1,_Ty2>' (or there is no acceptable conversion)". 
Any suggestion ? Is it the right way to switch from in_memory method to local_disk method ?
Thanks.

**Comment by cdmh** [comment]
Are you compiling one of the samples? What compiler toolset are you using?

**Comment by zbhuang** [comment]
Here is what I did.
I am using vs2012 to load your project in since it has vs2012 sln file there.
I am playing with your wordcount example on top of your mapreduce framework.
Replacing "schedule_policy::cpu_parallel" with "schedule_policy::sequential" in mapreduce.hpp is fine, I can build and run it. But replacing "intermediates::in_memory" with "intermediates::local_disk" in job.hpp makes the wordcount build fail.

**Comment by cdmh** [comment]
mapreduce.hpp and job.hpp is a part of the library - you don't want to change them. You select both the schedule policy and the intermediate store through template parameters of the mapreduce::job class.

The examples in wordcount.cpp at lines 312 and 331 both use the local_disk storage. Line 179 selects the schedule_policy::sequential for a debug build.

**Comment by zbhuang** [comment]
Thanks for your point.
Actually I was reading your old version of wordcount (boost version), did not realize such change in the wordcount.cpp.
By the way, do you have a plan to keep a updated version using boost (instead of c++11) ?

**Comment by cdmh** [comment]
No, the Boost version is now obsolete. The latest and maintained version is this one. Thanks for using it :)
