### ISSUE TITLE
Port to gcc

### ISSUE THREAD

**Issue by Manicqin** [cdmh/mapreduce#7]
Hello, I'm trying to port the code to GCC (Linux) and I'm having compiler issues (mainly template deducing issues).

Is there a GCC version that will successfully compile or an old commit that will compile?

thanks.

**Comment by cdmh** [comment]
It was tested well on bcc when first written, so I imagine a more recent change has broken gcc.
You could try 
https://github.com/cdmh/mapreduce/commit/b8de1cc73a04b9539b547c2935b9d33005e11cdf as a most likely candidate. Sorry I don’t have a gcc setup to hand. Let me know how you get on

**Comment by Manicqin** [comment]
Hi

I successfully compiled the latest code, I will fork and send you a couple of PRs to make the code more cross.

In order to make the entire project cross it will take other changes (cmake and different directory structure).

Thanks!
